blank_issues_enabled: true

contact_links:
  - name: ğŸŒ¸ p5.js Library Issues
    url: https://github.com/processing/p5.js/issues
    about: Report issues with the p5.js here.
  - name: ğŸ–¥ï¸ Web Editor Issues
    url: https://github.com/processing/p5.js-web-editor/issues
    about: Report issues with the p5.js web editor here.
  - name: ğŸ’¬ Forum
    url: https://discourse.processing.org/c/p5js
    about: Have other questions about using p5.js? Ask them here!